name: Build and deploy Node.js app to Azure Web App - omniplexai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Enable Corepack and install dependencies
        run: |
          corepack enable
          yarn install
      - name: Build application
        run: yarn build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          NEXT_PUBLIC_STRIPE_PRO_CHECKOUT_URL: ${{ secrets.NEXT_PUBLIC_STRIPE_PRO_CHECKOUT_URL }}


      - name: Verify build output
        run: |
          echo "=== BUILD VERIFICATION ==="
          echo "Checking if .next directory exists..."
          if [ ! -d ".next" ]; then
            echo "❌ ERROR: .next directory not found after build!"
            echo "Available files in current directory:"
            ls -la
            exit 1
          fi
          
          echo "✅ .next directory found"
          echo "Checking for standalone output..."
          if [ ! -d ".next/standalone" ]; then
            echo "❌ ERROR: .next/standalone directory not found!"
            echo "Contents of .next directory:"
            ls -la .next/
            exit 1
          fi
          
          echo "✅ Standalone build verified"
          echo "Contents of .next/standalone:"
          ls -la .next/standalone/

      - name: Prepare deployment package for standalone build
        run: |
          chmod +x ./azure-nextjs-deploy.sh
          ./azure-nextjs-deploy.sh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            deployment-package/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./deployment

      - name: Rename next-build back to .next
        run: |
          echo "🔄 Renaming next-build back to .next for Azure deployment..."
          if [ -d "./deployment/next-build" ]; then
            mv ./deployment/next-build ./deployment/.next
            echo "✅ Successfully renamed next-build to .next"
          else
            echo "❌ ERROR: next-build directory not found!"
            echo "Contents of deployment directory:"
            ls -la ./deployment/
            exit 1
          fi

      - name: Verify deployment structure (DO NOT RENAME HERE)
        run: |
          echo "=== DEPLOYMENT VERIFICATION ==="
          echo "Contents of deployment directory:"
          ls -la ./deployment/
          echo ""
          echo "Check for .next directory:"
          if [ -d ./deployment/.next ]; then
            echo "✅ .next directory found"
            ls -la ./deployment/.next/
          else
            echo "❌ .next directory NOT found"
            exit 1
          fi
          echo ""
          echo "Check for BUILD_ID:"
          if [ -f ./deployment/.next/BUILD_ID ]; then
            echo "✅ BUILD_ID found with content:"
            cat ./deployment/.next/BUILD_ID
          else
            echo "❌ BUILD_ID NOT found"
            exit 1
          fi
          echo ""
          echo "Check for server.js:"
          if [ -f ./deployment/server.js ]; then
            echo "✅ server.js found"
          else
            echo "❌ server.js not found"
            exit 1
          fi
          echo ""
          echo "Check for pages-manifest.json:"
          if [ -f ./deployment/.next/server/pages-manifest.json ]; then
            echo "✅ pages-manifest.json found"
          else
            echo "❌ pages-manifest.json NOT found - this will cause the app to fail"
            echo "Contents of .next/server:"
            ls -la ./deployment/.next/server/ || echo "No server directory"
            exit 1
          fi
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A710D8AC2F3C4741A1D3BAE272225977 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_598B45F58F3E411F843535247B69A342 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_86687C770A2743D7845F1E5D6BA93A8C }}
          

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omniplexai'
          slot-name: 'Production'
          package: ./deployment