# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - omniplexai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Enable Corepack and install dependencies
        run: |
          corepack enable
          yarn install

      - name: Build application
        run: yarn build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Prepare deployment package for standalone build
        run: |
          mkdir deployment-package
          
          # Copy the standalone server and its dependencies
          cp -R .next/standalone/* deployment-package/
          
          # Copy static files to the standalone build
          mkdir -p deployment-package/.next/static
          cp -R .next/static/* deployment-package/.next/static/
          
          # Copy public folder
          cp -R public deployment-package/public
          
          # Copy package.json for yarn start command
          cp package.json deployment-package/
          
          # Copy yarn.lock for consistency
          cp yarn.lock deployment-package/
          
          # Verify the structure
          echo "Deployment package structure:"
          ls -la deployment-package/
          echo "Checking .next directory:"
          ls -la deployment-package/.next/ || echo ".next directory not found"
          echo "Checking for server.js:"
          ls -la deployment-package/server.js || echo "server.js not found"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package/*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./deployment

      - name: Verify deployment structure
        run: |
          echo "Contents of deployment directory:"
          ls -la ./deployment/
          echo "Checking for server.js:"
          ls -la ./deployment/server.js || echo "server.js not found"
          echo "Checking for .next directory:"
          ls -la ./deployment/.next/ || echo ".next directory not found"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A710D8AC2F3C4741A1D3BAE272225977 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_598B45F58F3E411F843535247B69A342 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_86687C770A2743D7845F1E5D6BA93A8C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omniplexai'
          slot-name: 'Production'
          package: ./deployment